name: Build

on:
  push:
    branches:
      - "**"
      - "!json_update"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 21
          distribution: adopt
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.2.1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.1
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: gradle build
