name: Build

on:
  push:
    branches:
      - "**"
      - "!json_update"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 21
          distribution: adopt
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.2.2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.2
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: gradle build
